name: Check Shell Scripts

on:
  push:
    branches:
      - main
      - 'renovate/**'
    paths:
      - '**.sh'
      - '**.bash'
      - '**.mksh'
      - '**.bats'
      - '**.zsh'
      - '.githooks/*'

  pull_request:
    branches:
      - main
    paths:
      - '**.sh'
      - '**.bash'
      - '**.mksh'
      - '**.bats'
      - '**.zsh'
      - '.githooks/*'

  workflow_dispatch:
  workflow_call:

jobs:
  code-quality:
    name: Code Quality

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Check out repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Set up shellcheck
        env:
          # renovate: datasource=github-releases depName=koalaman/shellcheck
          SHELLCHECK_VERSION: v0.11.0
          # renovate: datasource=github-releases depName=lumaxis/shellcheck-problem-matchers
          SHELLCHECK_PROBLEM_MATCHERS_VERSION: v2.1.0
        run: |
          set -o nounset -o xtrace

          # Download, extract and set mode for shellcheck.
          wget -q "https://github.com/koalaman/shellcheck/releases/download/${SHELLCHECK_VERSION}/shellcheck-${SHELLCHECK_VERSION}.linux.x86_64.tar.xz" \
            -O shellcheck.tar.xz
          tar -xf shellcheck.tar.xz
          mv "shellcheck-${SHELLCHECK_VERSION}/shellcheck" shellcheck
          chmod +x shellcheck

          # Download and register problem matcher for shellcheck.
          wget -q "https://raw.githubusercontent.com/lumaxis/shellcheck-problem-matchers/${SHELLCHECK_PROBLEM_MATCHERS_VERSION}/.github/shellcheck-gcc.json" \
            -O shellcheck-problem-matcher.json
          echo "::add-matcher::shellcheck-problem-matcher.json"

      - name: Run shellcheck
        run: |
          set -o nounset -o xtrace
          # Support advanced globbing patterns.
          shopt -s nullglob globstar

          # We have to use gcc format and disable colors for the problem matcher.
          ./shellcheck --norc --enable=all --format=gcc --color=never \
            ./**/*.{sh,bash,mksh,bats,zsh} \
            .githooks/*
